export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const CART_TOTAL_AMOUNT = "CART_TOTAL_AMOUNT";

export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";

export const GET_CARTS_SUCCESS = "GET_CARTS_SUCCESS";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";

export const GET_EDIT_CHOICES = "GET_EDIT_CHOICES";
export const GET_EDIT_CHOICE = "GET_EDIT_CHOICE";
export const CHANGE_EDIT_CHOICE = "CHANGE_EDIT_CHOICE";

export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";